
from pyautogui import size , position
from cv2 import cv2
import numpy as np

import pytesseract as tess

tess.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract'


file = open("syntax.txt","r")
p = file.read()

file.close()

file_css = open("index_css.css",'w')
file_css.write("/* this is a css file for index.html ( auto generated by code) */ ")

file_css.close()

# init html file /  body


file_html = open("index.html", "w")
start_ind = p.find("{Body-init}") + 12
end_ind = p.find("{end}",start_ind+12)
file_html.write(p[start_ind:end_ind])
file_html.close()



file_html = open("index.html",'a')


file_css = open("index_css.css", "a")
start_ind = p.find("{css_init}") + 10
end_ind = p.find("{end}",start_ind+12)
file_css.write(p[start_ind:end_ind])








img1 = cv2.imread("p6.png",0)
img2 = img1.copy()



corner = cv2.goodFeaturesToTrack(img1, 70, .0001 , 21)

res, thres = cv2.threshold(img1,120,255,cv2.THRESH_BINARY_INV)
cv2.imshow("thres",thres)

cnts , heir = cv2.findContours(thres,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

img = cv2.drawContours(img1,cnts,-1,(176,10,15),4)
Cnts_Area = []

Cnts_Mid = []
data2 = []
for c in cnts:

    m = cv2.moments(c)

    area = cv2.contourArea(c)

    if area > 700:
        c_x = int(m["m10"]/m["m00"])
        c_y = int(m["m01"]/m["m00"])
        for i in Cnts_Mid:
            if i[0] == c_y and i[1] == c_x:
                break
        else:
            Cnts_Area.append(area)
            Cnts_Mid.append([c_y,c_x])

    cv2.drawContours(img,[c],-1,(0,255,0))



corner = np.int64(corner)
coords = []
for i in corner:
    x,y = i.ravel()
    coords.append([y,x])
    cv2.circle(img1, (x,y),3,55,-1)


coords.sort()


for i in range(len(coords)-1):
    y,x = coords[i]
    y2,x2 = coords[i+1]
    if ( y-5 < y2 < y+5 and x>x2):
        temp = coords[i+1]
        coords[i+1] = coords[i]
        coords[i] = temp






screen_size_x, screen_size_y = size()
form_st_coords = coords[0]
form_end_coords = coords[-1]
print(coords)
print("form_St", form_st_coords)
print("form_end ", form_end_coords)
# -------------- div ------------

start_ind = p.find("{form_div}")+ 10
end_ind = p.find("{end}",start_ind)
syntax = p[start_ind:end_ind].format(id = "form_div")

file_html.write(syntax)



start_ind = p.find("{css-div}")+ 10
end_ind = p.find("{end}",start_ind)
syntax = p[start_ind:end_ind]
perc_w = ((form_end_coords[1]- form_st_coords[1])/ screen_size_x) *100
perc_w = round(perc_w, ndigits=3)
marg = (100 - perc_w) /2
marg = round(marg, ndigits=3)
syntax = syntax.format(id = "form_div", width = f"{perc_w}%" , left_m = f"{marg}%")
syntax = syntax.replace("<<","{")
syntax = syntax.replace(">>","}")
file_css.write(syntax)







# form body layout ---------
start_ind = p.find("{form_init}") + 12
end_ind = p.find("{end}",start_ind)
syntax = p[start_ind:end_ind]
file_html.write(syntax.format(id = "form_init"))
print("-------- form body initialized ------")





start_ind = p.find("{css-id}")+ 8
end_ind = p.find("{end}",start_ind)
syntax = p[start_ind:end_ind]
syntax = syntax.format(id = "form_init", width = "96% ")
syntax = syntax.replace("<<","{")
syntax = syntax.replace(">>","}")
file_css.write(syntax)


input_boxes_coords = []


for i in (Cnts_Mid):
    y_mid,x_mid = i



    for j in range(len(coords)-1):
        y_coords,x_coords = coords[j]

        diff_y = y_mid - y_coords
        diff_x = x_mid - x_coords

        if diff_x > 0 and diff_y > 0 :
            for t in range(j+1,len(coords)):
                y_2_coords,x_2_coords = coords[t]

                if diff_y + 6 >=y_2_coords - y_mid >= diff_y- 6 and diff_x +  6>= x_2_coords - x_mid >= diff_x- 6 :


                    if (y_coords != coords[0][0] and x_coords != coords[0][1]):
                        input_boxes_coords.append([y_coords,x_coords,y_2_coords,x_2_coords ])
                        cv2.rectangle(img1, (x_coords,y_coords),(x_2_coords,y_2_coords),(0,0,255),4)

input_boxes_coords.sort()
#for i,e in enumerate(input_boxes_coords):
   # print(i)
  #  cv2.putText(img1,str(i),(e[1],e[0]),cv2.FONT_HERSHEY_SIMPLEX,5,(0,155,255),cv2.LINE_AA)

# ----------------------- input / label loop ------------




for i in range(len(input_boxes_coords)):

    img2[input_boxes_coords[i][0]: input_boxes_coords[i][2] ,input_boxes_coords[i][1]: input_boxes_coords[i][3]] = [255]


tex = tess.image_to_string(img2,lang='eng',config='--psm 6')
tex = tex.replace("\n", " ")
keywords_search = tex.split(" ")

print(keywords_search)
keywords_search = list(keywords_search)
del img2

keyword_list = ["name", "button", "checkbox", "color", "phone","date","datetime", "email", "file","hidden","image","month","password","radio","range","reset","search","submit","tel","time","url"]
for i in  keywords_search:
    if i not in keyword_list:
        keywords_search.remove(i)

print(keywords_search)



for i in range(len(input_boxes_coords)):
   # img_cut = img1[ input_boxes_coords[i][0]: input_boxes_coords[i][2] ,input_boxes_coords[i][1]: input_boxes_coords[i][3]]

   # tex = tess.image_to_string(img_cut, lang='eng', config='--psm 6')
   # print("text =  ",tex)
   # cv2.imshow(f"win{i}", img_cut)
    keyword_input = keywords_search[i]
    width = input_boxes_coords[i][3] - input_boxes_coords[i][1]
    width = round(width,ndigits= 3)

    perc_w = (width/(form_end_coords[1]- form_st_coords[1])) * 100
    perc_w = round(perc_w, ndigits= 3)

    margin_left = ((input_boxes_coords[i][1] - form_st_coords[1])/ (form_end_coords[1]- form_st_coords[1])) * 100
    margin_left = round(margin_left, ndigits=3)
    if (keyword_input == "name"):

    # ----------- label ---------------
        start_ind = p.find("{form_label}")+ 12
        end_ind = p.find("{end}",start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input = f"text_{i}", label_id = f"name_label{i}", string_label = "name")
        file_html.write(syntax)

    # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id = f"name_label{i}",margin_left = f"{margin_left}%",font_size = "20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    # ----------- input  ---------------
        start_ind = p.find("{form_name}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"text_{i}", name_label= f"text_{i}")
        file_html.write(syntax)


    # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id = f"text_{i}", margin_bott = "20px",margin_left = f"{margin_left}%",width = f"{perc_w}%" , height = "20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)



    if (keyword_input == "button"):

    # ----------- label ---------------
        start_ind = p.find("{form_label}")+ 12
        end_ind = p.find("{end}",start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input = f"button_{i}", label_id = f"button_label{i}", string_label = "Button")
        file_html.write(syntax)

    # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id = f"button_label{i}",margin_left = f"{margin_left}%",font_size = "20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    # ----------- input  ---------------
        start_ind = p.find("{form_button}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"button_{i}", name_label= f"button_{i}")
        file_html.write(syntax)


    # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id = f"button_{i}", margin_bott = "20px",margin_left = f"{margin_left}%",width = f"{perc_w}%" , height = "20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)





    if (keyword_input == "phone"):

    # ----------- label ---------------
        start_ind = p.find("{form_label}")+ 12
        end_ind = p.find("{end}",start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input = f"phone_{i}", label_id = f"phone_label{i}", string_label = "Phone")
        file_html.write(syntax)

    # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id = f"phone_label{i}",margin_left = f"{margin_left}%",font_size = "20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    # ----------- input  ---------------
        start_ind = p.find("{form_number}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"phone_{i}", name_label= f"phone_{i}")
        file_html.write(syntax)


    # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id = f"phone_{i}", margin_bott = "20px",margin_left = f"{margin_left}%",width = f"{perc_w}%" , height = "20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)




    if (keyword_input == "checkbox"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"checkbox_{i}", label_id=f"checkbox_label{i}", string_label="Checkbox")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"checkbox_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_checkbox}") + 15
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"checkbox_{i}", name_label=f"checkbox_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"checkbox_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

    if (keyword_input == "color"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"color_{i}", label_id=f"color_label{i}", string_label="Color")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"color_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_color}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"color_{i}", name_label=f"color_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"color_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)




    if (keyword_input == "date"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"date_{i}", label_id=f"date_label{i}", string_label="Date")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"date_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_date}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"date_{i}", name_label=f"date_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"date_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)



    if (keyword_input == "datetime"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"datetime_{i}", label_id=f"datetime_label{i}", string_label="datetime")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"datetime_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_datetime}") + 15
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"datetime_{i}", name_label=f"datetime_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"datetime_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    if (keyword_input == "email"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"email_{i}", label_id=f"email_label{i}", string_label="email")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"email_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_email}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"email_{i}", name_label=f"email_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"email_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    if (keyword_input == "file"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"file_{i}", label_id=f"file_label{i}", string_label="file")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"file_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_file}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"file_{i}", name_label=f"file_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"file_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    if (keyword_input == "hidden"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"hidden_{i}", label_id=f"hidden_label{i}", string_label="hidden")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"hidden_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_hidden}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"hidden_{i}", name_label=f"hidden_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"hidden_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    if (keyword_input == "image"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"image_{i}", label_id=f"image_label{i}", string_label="image")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"image_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_image}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"image_{i}", name_label=f"image_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"image_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    if (keyword_input == "month"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"month_{i}", label_id=f"month_label{i}", string_label="month")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"month_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_month}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"month_{i}", name_label=f"month_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"month_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    if (keyword_input == "password"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"password_{i}", label_id=f"password_label{i}", string_label="password")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"password_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_password}") + 15
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"password_{i}", name_label=f"password_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"password_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    if (keyword_input == "radio"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"radio_{i}", label_id=f"radio_label{i}", string_label="radio")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"radio_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_radio}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"radio_{i}", name_label=f"radio_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"radio_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    if (keyword_input == "range"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"range_{i}", label_id=f"range_label{i}", string_label="range")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"range_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_range}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"range_{i}", name_label=f"range_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"range_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    if (keyword_input == "reset"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"reset_{i}", label_id=f"reset_label{i}", string_label="reset")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"reset_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_reset}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"reset_{i}", name_label=f"reset_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"reset_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    if (keyword_input == "search"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"search_{i}", label_id=f"search_label{i}", string_label="search")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"search_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_search}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"search_{i}", name_label=f"search_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"search_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    if (keyword_input == "submit"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"submit_{i}", label_id=f"submit_label{i}", string_label="submit")
        print(syntax)
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"submit_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_submit}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"submit_{i}", name_label=f"submit_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"submit_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)



    if (keyword_input == "telephone"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"telephone_{i}", label_id=f"telephone_label{i}", string_label="telephone")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"telephone_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_telephone}") + 16
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"telephone_{i}", name_label=f"telephone_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"telephone_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)




    if (keyword_input == "time"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"time_{i}", label_id=f"time_label{i}", string_label="time")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"time_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_time}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"time_{i}", name_label=f"time_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"time_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


    if (keyword_input == "url"):
        # ----------- label ---------------
        start_ind = p.find("{form_label}") + 12
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(name_input=f"url_{i}", label_id=f"url_label{i}", string_label="url")
        file_html.write(syntax)

        # ---------label css ---------------

        start_ind = p.find("{label_css}") + 13
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(label_id=f"url_label{i}", margin_left=f"{margin_left}%", font_size="20px")
        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)

        # ----------- input  ---------------
        start_ind = p.find("{form_url}") + 10
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"url_{i}", name_label=f"url_{i}")
        file_html.write(syntax)

        # ----------- input css  ---------------
        start_ind = p.find("{css-input}") + 11
        end_ind = p.find("{end}", start_ind)
        syntax = p[start_ind:end_ind]
        syntax = syntax.format(id=f"url_{i}", margin_bott="20px", margin_left=f"{margin_left}%", width=f"{perc_w}%",
                               height="20px")

        syntax = syntax.replace("<<", "{")
        syntax = syntax.replace(">>", "}")
        file_css.write(syntax)


cv2.imshow("res",img1)
file_html.write("</div>")

start_ind = p.find("{body_ter}") + 10
end_ind = p.find("{end}", start_ind)
syntax = p[start_ind:end_ind]
file_html.write(syntax)

file_html.close()
file_css.close()

cv2.waitKey()
